#
# Makefile for OTF.
#

obj-$(CONFIG_SPICA_OTF)		+= spica.o
obj-$(CONFIG_OTF_VDE)		+= otf_vde.o
obj-$(CONFIG_OTF_CPU1)		+= otf_cpu1.o
obj-$(CONFIG_OTF_DDR2MIN)	+= otf_ddr2min.o
obj-$(CONFIG_OTF_LPDDR2)	+= otf_lpddr2.o
obj-$(CONFIG_OTF_GPU)		+= otf_gpu.o
obj-$(CONFIG_OTF_AVP)		+= otf_avp.o
obj-$(CONFIG_OTF_PSNIT)		+= otf_psnit.o
obj-$(CONFIG_OTF_MAXSCOFF)	+= otf_maxscoff.o
